##########################
#      CustomWelcome     #
##########################
# Author: Beeted_
# Version: 1.9

# Users need permissions to see join, quit, and motd messages.
# To see the list of permissions go to the CustomWelcome Spigot page: https://www.spigotmc.org/resources/%E2%AD%90-customwelcome-%E2%AD%90-customize-join-leave-motd-messages.108510/

# Requires PlaceholderAPI installed: https://www.spigotmc.org/resources/placeholderapi.6245/
# To see the available variables: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders

# Join and Quit config.
config:
  enable-join-message: true #Set this to false for disable the message.
  join-message: "&7[&a+&7] &bPlayer &d%player_name% &bhas joined the server."
  enable-quit-message: true #Set this to false for disable the message.
  quit-message: "&7[&c-&7] &bPlayer &d%player_name% &bhas left the server."
  enable-first-join-message: true #Set this to false for disable the message.
  first-join-message: "&7[&a+&7] &bPlayer &d%player_name% &bis new on the server. &7(&8#%player_count%&7)"

# MOTD config.
motd:
  enable-motd-message: true #Set this to false for disable the message.
  motd-message:
  - "&7&m▶----------------------------◀"
  - "&d        &8[&6✦&8] &dExample Server &8[&6✦&8]"
  - "&f         Welcome back &b%player_name%"
  - ""
  - "&e            www.example.com"
  - "&7&m▶----------------------------◀"

server-list-motd:
  enable-server-list-motd-message: true #Set this to false for disable the message.
  message: "&aWelcome to the server! Visit our website at www.your-site.com"

player-count: 0 # It is recommended not to touch this parameter.
